language: python
python:
- "2.6"
- "2.7"
- "3.2"
- "3.3"
- "3.4"
- "pypy"
- "pypy3"
env:
  - DJANGO="DJANGO>=1.4.0,<1.5.0"
  - DJANGO="DJANGO>=1.5.0,<1.6.0"
  - DJANGO="DJANGO>=1.6.0,<1.7.0"
  - DJANGO="DJANGO>=1.7.0,<1.8.0"
install:
  - pip install $DJANGO
  - if [[ $TRAVIS_PYTHON_VERSION == 2* || $TRAVIS_PYTHON_VERSION == 3.2 || $TRAVIS_PYTHON_VERSION == pypy* ]]; then pip install mock; fi
script:
  - python setup.py develop
  - python manage.py test --settings=tests.support.settings

matrix:
  exclude:
    - python: "3.2"
      env: DJANGO="DJANGO>=1.4.0,<1.5.0"
    - python: "3.3"
      env: DJANGO="DJANGO>=1.4.0,<1.5.0"
    - python: "3.4"
      env: DJANGO="DJANGO>=1.4.0,<1.5.0"
    - python: "pypy"
      env: DJANGO="DJANGO>=1.4.0,<1.5.0"
    - python: "pypy3"
      env: DJANGO="DJANGO>=1.4.0,<1.5.0"
    - python: "2.6"
      env: DJANGO="DJANGO>=1.7.0,<1.6.0"
  fast_finish: true